### ISSUE TITLE
Thanks for the project

### ISSUE THREAD

**Issue by mallowigi** [LorisSigrist/zocker#21]
Not an issue, I'm just glad that you poured time on this project. I hope it stays maintained in the future!

**Comment by jgarplind** [comment]
> Not an issue, I'm just glad that you poured time on this project. I hope it stays maintained in the future!

I came here to share the same sentiment, and couldn't find a better place to do so.

Zocker has been extremely useful for us in making our test setup clean and reliable.

My only worry now is that we may become too dependent on Zocker, causing us pain in a scenario where TS/Zod evolves and Zocker is somehow left behind.

Still, with that risk in mind, it is a huge boon for us to be able to use your library.

Thanks!
